### ISSUE TITLE
LOGIN: Anmeldeseite intuitiver gestalten (W1)

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_glp#34]
Als Person, die sich bei der Hitobito-Instanz der GLP registrieren oder anmelden will, wünsche ich mir eine Anmeldeseite, die jener von [Digitec](https://id.digitecgalaxus.ch/login) ähnelt, damit sich die Anmeldung intuitiv gestaltet.

Neu soll sich die Anmeldeseite zweigeteilt präsentieren.

Auf der linken Seite soll sich "erstmaliger Login" befinden. Hier gibt es einen Button für das Setzen des Passwortes. Zudem soll eine kurze Erklärung ersichtlich sein, für Mitglieder oder Sympathisanten, die Hitobito noch nicht benutzt haben.

Auf der rechten Seite soll sich "Anmelden" befinden.  Hier wird das normale Login wie bisher angezeigt, inklusive der Option "Passwort vergessen".

Optional:
Ein Link auf eine Erklärung des 2FA-Logins mit einer Hilfe bei Problemen.

# Tech-Spec

- Anmeldeseite orientiert sich optisch der von Digitec
- Anmeldeseite ist insbesondere für Hitobito Neukunden intuitiver
- Linke und Rechte Seite entsprechen **NICHT** der Digitec-Loginseite, sondern dem Kundenwunsch

# ToDo

- [x] Anmeldeseite wird zweispaltig gestaltet
- [x] Rechte Seite für Anmeldung wie bisher
- [x] Linke Seite mit Erklärung und Button der zum Passwort-Reset führt
- [x] Erklärung ist CustomContent "Login Informationen" (`views/devise/sessions/info`)
- [x] Link für [2FA](https://hitobito.readthedocs.io/de/latest/two_factor_authentication.html) Q&A
- [x] Mit angemessener Rolle "durchklicken"
- [ ] Hinweis an Kunden, dass Login-Informationen und "Einstellungen -> Texte" bearbeitet werden können
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sampmueller** [comment]
Könntet Ihr das bitte wieder aktivieren, damit wir es noch prüfen können auf notwendige Anpassungen?

**Comment by sampmueller** [comment]
- Bitte Button «Erstes Login? Hier Passwort setzen» nach oben nehmen und 2FA-Link dafür nach unten
- Bitte Hinweis auf 2FA wie folgt anpassen: Hier gehts zur Erklärung des 2FA-Logins (nicht notwendig, wenn Du keine andere Rolle als Mitglied oder Sympathisant:in hast!): https://hitobito.readthedocs.io/de/latest/two_factor_authentication.html
- Ich habe einen Vorschlag zur Anpassung der 2FA-Anleitung gemacht. Könnt Ihr das sehen?
- Übersetzungen auf F und I fehlt noch, gerne tragen wir diese in Transifex ein, sobald es dort hinterlegt sind.
- Sobald der Text der Anleitung final ist, organisiert die GLP Schweiz die Übersetzung. 1. Frage: Wie können wir die am besten Frage: existiert schon eine Übersetzung des Textes, der aktuell online ist, auf Franz. oder Ital.?

**Comment by mlue00** [comment]
Welchen Text im roten Balken sprichst du bei der Anmeldeseite an? Diesen konnte ich nicht finden.
Die Positionierungen oder Texte anzupassen wird schnell erledigt sein.
Deinen Vorschlag für die Anleitung kann ich leider nicht sehen. Dafür müsstest du einen Pull Request auf dem entsprechenden Github-Repo erstellen. Wie und wo hast du den Vorschlag erstellt?

**Comment by sampmueller** [comment]
![image](https://github.com/hitobito/hitobito_glp/assets/63230679/ad9422cd-45f9-405e-be89-bfb2bb330577)

**Comment by sampmueller** [comment]
![image](https://github.com/hitobito/hitobito_glp/assets/63230679/ad9422cd-45f9-405e-be89-bfb2bb330577)
Ich meine diesen Text, aber wenn für die Anpassung unverhältnismässiger Aufwand (mehr als eine Stunde) entsteht, lassen wir es so, wie es ist.
Hier mein Pull Request, ich finde leider gerade nicht heraus, wie ich zu meinem Textvorschlag komme. Aber ich habe den Erklärtext geöffnet und habe dann "Edit on github" ausgewählt und einen alternativen Textvorschlag erfasst:
![image](https://github.com/hitobito/hitobito_glp/assets/63230679/66a39a68-5ebd-4693-a0b9-a0fb771e015a)
