### ISSUE TITLE
Anpassungen Formular GLP

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_glp#38]
Dies ist ein Folgeticket zu https://github.com/hitobito/hitobito_glp/issues/32 
Im Rahmen dieses Issues sollen weitere Korrekturen an den Anmeldeformularen der GLP vorgenommen werden.

Bei der Auswahl "keine Angabe" des Geschlechts ist es aktuell so, dass anschliessend die Meldung "kein gültiger Wert" erscheint.
"Keine Angabe" ist aber ein Gültiger Wert und soll als solchen akzeptiert werden.

![image](https://user-images.githubusercontent.com/69250571/214822104-49d57d31-3bfa-4e57-bf30-df18eb4b8bb5.png)

Wenn das Formular erfolgreich übermittelt wurde, wird auf der nächsten Seite lediglich ein weisser Balken angezeigt.
Hier sollte jedoch eine Meldung erscheinen, die die erfolgreiche Übermittelung bestätigt.
Zudem sollte sichergestellt werden, dass nicht automatisch ans Ende dieser Seite gescrollt wird.

![image](https://user-images.githubusercontent.com/69250571/214822654-a2bfc5d1-cd6e-4dcb-97bb-a177a695ea22.png)

## Tech-Spec
- [ ] Umsetzung/Fixen im glp Wagon

## ToDo:
- [ ] https://github.com/hitobito/hitobito_glp/blob/master/app/controllers/external_forms_controller.rb#L156 value zu leer (nil) ändern
  - [ ] Prüfen ob das beim `Person.new(attrs)` auch richtig assigned wird: https://github.com/hitobito/hitobito_glp/blob/master/app/controllers/externally_submitted_people_controller.rb#L51
  - [ ] Specs ergänzen: https://github.com/hitobito/hitobito_glp/blob/master/spec/controllers/externally_submitted_people_controller_spec.rb
- [ ] https://github.com/hitobito/hitobito_glp/blob/master/app/views/external_forms/loader.js.erb#L39 debuggen weshalb da nichts displayed wird.

**Comment by sampmueller** [comment]
Wie besprochen:
- Nach Abschicken des Formulars (alle Typen) kommt ein weisser Balken und der Bestätigungstext ist kaum erkennbar oberhalb des leeren weissen Balkens 

Sollte noch angepasst werden:
- Meldung «Klicke dieses Kästchen an, wenn Du fortfahren möchtest» erscheint im franz. Form. nicht auf Franz. und im ital. Form nicht auf Ital. Falls Ihr die Übersetzung braucht, einfach kurz bei uns melden. Franz. hätte ich schon: Cochez cette case pour cotinuer.

Nicht unbedingt nötig, aber nice to have (bevor Ihr hier Aufwand betreibt, bitte mit uns absprechen):
- «Haupt-E-Mail ist nicht gültig» oder «Deine E-Mail-Adresse ist leider schon vergeben. Melde Dich unter +41 31 311 33 03 oder [schweiz@grunliberale.ch](mailto:schweiz@grunliberale.ch), damit wir Dich zum Mitglied upgraden bzw. Dir bei Deinem Anliegen weiterhelfen können» erscheinen ganz oben (dieses Problem besteht bereits beim bestehenden Formular, ev. können wir das auch lassen, es ist aber sicher keine gute UX).
- Desktop & Mobile: Nach Abschicken des Formulars (alle Typen) lande ich unten auf der Seite und sehe keine Bestätigung (dieses Problem besteht bereits beim bestehenden Formular, ev. können wir das auch lassen, es ist aber sicher keine gute UX)
- Sowohl Desktop- als auch Mobilansicht: etwas zu viel Abstand zwischen Formular-Beginn (weisse Fläche) und erstem Feld (Vorname)

**Comment by mlue00** [comment]
test
