### ISSUE TITLE
PEOPLE: Anpassungen Spender:innen-Verwaltung

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_glp#42]
Im Rahmen diese Issues sollen Nacharbeiten und Anpassungen zu #33 vorgenommen werden.

Aktuell ist es für Spendenverwalter:innen nicht möglich neue Speder:innen auf den Sublayer zu erfassen. Dies soll neu ermöglicht werden. Die Rechte auf allen darunterliegenden Layer sollen sich hier analog zu jenen der Admins verhalten.

Das Erstellen von neuen Spenderverwalter:innen soll nur für Spendenverwalter:innen der Ebene GLP Schweiz möglich sein. Auch hier sollen sich die Berechtigungen analog zu jenen der Admins verhalten.

Wenn sich ein:e Spender:in bei Hitobito einloggt, soll diese:r eine vereinfachte Darstellung von Hitobito sehen. Die Ansicht soll die gleiche sein, wie jene, die bei den Sympatisant:innen und Mitglieder erscheint.

# TODO
- [x] In https://github.com/hitobito/hitobito_glp/blob/master/app/abilities/glp/role_ability.rb#L31 die Spendenverwalter:innen-Rollen in die Liste von "precious roles" eintragen
- [x] Bei allen bestehenden Spendenverwalter-Rollen die Permission `:layer_full` durch `:layer_and_below_full` ersetzen, damit sie auch Spender:innen auf Sub-Layern erfassen und verwalten können
- [x] Im Cevi-Wagon global nach `unconfined_below` suchen, und alles relevante in den Core übernehmen. Vorschlag für Umbenennung: `manage_invisible_people`. für die Spendenverwalter:innen der GLP übernehmen. `:unconfined_below` ist eine Permission beim Cevi, die es erlaubt, das `visible_from_above: false` zu umgehen, welches wir auf den GLP-Spendern haben. Verschiebung in den Core, weil SWW auch etwas ähnliches braucht.
- [x] Wenn `unconfined_below` vom Cevi Wagon in den Core verschoben wird, noch Dokumentation für diese Permission schreiben
- [x] In https://github.com/hitobito/hitobito_glp/blob/master/app/models/glp/person.rb#L13 auch alle Spender:innen-Rollen aller Ebenen aufnehmen
- [ ] ~~Untersuchen, warum Sam in der Personenliste der Spendergruppen keine Spender-Rollen sieht. Das ist vermutlich wegen `visible_from_above: false` so, aber dann sollte er die Spender überhaupt nicht in dieser Gruppe aufgelistet sehen.~~ extrahiert in ticket #44

**Comment by sampmueller** [comment]
"Aktuell ist es für Spendenverwalter:innen nicht möglich neue Speder:innen auf den Sublayer zu erfassen. Dies soll neu ermöglicht werden. Die Rechte auf allen darunterliegenden Layer sollen sich hier analog zu jenen der Admins verhalten."
Korrekt

_"Das Erstellen von neuen Spenderverwalter:innen soll nur für Spendenverwalter:innen der Ebene GLP Schweiz möglich sein. Auch hier sollen sich die Berechtigungen analog zu jenen der Admins verhalten."_
Präzisierung: Das Erstellen von neuen Spenderverwalter:innen soll **auf allen Ebenen** nur für Spendenverwalter:innen der Ebene GLP Schweiz möglich sein

_"Wenn sich ein:e Spender:in bei Hitobito einloggt, soll diese:r eine vereinfachte Darstellung von Hitobito sehen. Die Ansicht soll die gleiche sein, wie jene, die bei den Sympatisant:innen und Mitglieder erscheint."_
Ja, zur Präzisierung: Das gilt für Personen mit Rolle Spender:in, welche zusätzlich **nur** die Rolle Mitglied und/oder Sympathisant:in haben - der Vollständigkeit halber ergänze ich: Auch wenn das ein seltener Fall ist, es gilt auch für die Rolle "Medien & Dritte". Wenn eine Person mit Rolle Spender:in andere Rollen hat wie z.B. Admin, dann sieht sie natürlich die komplexere Baum-Ansicht. Ich glaube, die vereinfachte Ansicht ist im momentan für folgende Rollen aktiviert (sofern man keine andere Rolle hat:) Mitglied, Sympathisant:in, Medien & Dritte. Neu soll das auch für die Rolle Spender:in zutreffen. Stimmt das so oder habe ich etwas vergessen?

**Comment by carlobeltrame** [comment]
Danke für die Präzisierung. Was ist genau gemeint mit "Die Rechte auf allen darunterliegenden Layer sollen sich hier analog zu jenen der Admins verhalten"? Ich verstehe das wie in folgendem Satz illustriert, aber ich bin nicht sicher ob das wirklich korrekt ist:
Ein Spendenverwalter in einer Kantonalpartei hat dieselben Rechte wie ein Admin der Kantonalpartei. Stimmt diese Aussage wirklich? Was konkret muss ein Spendenverwalter auf kantonaler oder regionaler Ebene können? Einfach nur Spender:innen anlegen, bearbeiten und entfernen?

> Ich glaube, die vereinfachte Ansicht ist im momentan für folgende Rollen aktiviert (sofern man keine andere Rolle hat:) Mitglied, Sympathisant:in, Medien & Dritte. Neu soll das auch für die Rolle Spender:in zutreffen. Stimmt das so oder habe ich etwas vergessen?

Aus meiner Sicht hast du nichts vergessen, diese Anforderung scheint mir klar. Genau die drei von dir erwähnten Rollen bekommen bisher die vereinfachte Ansicht, und neu gilt das dann auch noch für Spender:innen-Rollen. Sobald jemand noch eine weitere Rolle ausserhalb dieser 4 hat, bekommt er/sie die vollständige Ansicht.

**Comment by carlobeltrame** [comment]
Und noch eine weitere Frage, müssen die Spendenverwalter:innen nur neue Spender:innen auf den Sub-Layern *erfassen* können, oder auch die bestehenden managen (sehen, bearbeiten, löschen) können? Ich muss es noch genauer abklären, aber das könnte noch einen signifikanten Einfluss auf den Aufwand haben.

**Comment by sampmueller** [comment]
> Danke für die Präzisierung. Was ist genau gemeint mit "Die Rechte auf allen darunterliegenden Layer sollen sich hier analog zu jenen der Admins verhalten"? Ich verstehe das wie in folgendem Satz illustriert, aber ich bin nicht sicher ob das wirklich korrekt ist: Ein Spendenverwalter in einer Kantonalpartei hat dieselben Rechte wie ein Admin der Kantonalpartei. Stimmt diese Aussage wirklich? Was konkret muss ein Spendenverwalter auf kantonaler oder regionaler Ebene können? Einfach nur Spender:innen anlegen, bearbeiten und entfernen?
> 
Als Spendenverwalter:in auf Ebene Kanton oder Bezirk muss ich Folgendes können:
- Spender:innengruppen auf der betreffenden Ebene und auf darunterliegenden Ebenen erstellen und bearbeiten
- In diesen Spender:innengruppen Spender:innen hinzufügen, bearbeiten und entfernen
- Anderen Spendenverwalter:innen auf der gleichen und tieferliegenden Ebene diese Rolle wegnehmen

Als Spendenverwalter:in auf Ebene Ort muss ich Folgendes können:
- Spender:innengruppen auf der gleichen Ebene erstellen und bearbeiten
- In diesen Spender:innengruppen Spender:innen hinzufügen, bearbeiten, entfernen
- Anderen Spendenverwalter:innen auf der gleichen Ebene diese Rolle wegnehmen

Als Spendenverwalter:in auf Ebene Kanton, Bezirk oder Ort darf ich Folgendes **nicht** können:
- Neue Spendenverwalter:innen hinzufügen, egal auf welcher Ebene [Neue Spendenverwalter:innen dürfen nur Spendenverwalter:innen auf Ebene Schweiz erstellen]

**Comment by daniel-illi** [comment]
Ich habe das ticket so umgesetzt wie spezifiziert (zumindest glaube ich das 🙃 ).

Allerdings habe ich im Nachhinein das Gefühl, dass das naming nicht passend ist, denn das neue `manage_invisible_people` gibt gar keine managing Rechte sondern ermöglicht lediglich, Einträge zu sehen (Anpassung an `PersonFetchables`/`PersonReadables`/`PersonLayerWritables`). 
Sollten wir vielleicht einer Person mit `manage_invisible_people` automatisch auch `layer_and_below_full` geben?

Ausserdem habe ich den letzten Punkt noch nicht erledigt, das "Untersuchen, warum Sam in der Personenliste der Spendergruppen keine Spender-Rollen sieht."
Mir fehlt das Wissen dazu um die beschriebene Situation zu reproduzieren.

**Comment by sampmueller** [comment]
Hier mein Testbericht (auch in Issue 44 gepostet)

Das Issue der nicht sichtbaren Rolle "Spender:in" besteht nach wie vor für Spendenverwalter:innen auf allen Ebenen. Anders wenn ich Spender:in bin und die Gruppe aufrufe, in der ich die Rolle habe, dann sehe ich mich selbst mit der Rolle Spender:in. Wenn ich auch die Berechtigung für die Gruppe habe, sehe ich die anderen Personen zwar in der Gruppe, aber nicht mit der Rolle.
Die Rolle Spender:in wurde noch nicht in die anderen Sprachen übersetzt (FR, EN, IT). Wird das noch gemacht? Fehlen noch Übersetzungen auf Transifex?

**Comment by mlue00** [comment]
https://github.com/hitobito/hitobito_glp/issues/44#issuecomment-1717656746
