### ISSUE TITLE
GLP-Integration: Daten löschen & neu Seeden

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_glp#57]
Die GLP hat noch viele alte Daten in ihrer Integrationsumgebung und keine genaue Übersicht mehr, was da noch alles vorhanden ist, und wer hier noch Zugriff hat.
Um diese nicht manuell bereinigen zu müssen, soll die Integration der GLP komplett gewipet und neu mit Standarddaten geseedet werden.

# Tech-Spec

- Neuanfang der Integrationsdaten

# ToDo

- [x] Integrationsumgebungsdaten löschen
- [x] neue Standartdaten Seeden
- [x] Niculin Detreköy als Admin erfassen & Passwort zustellen
- [x] Neues Root-User PW im Cryptopus hinterlegen
- [x] Kunde informieren (tel)
